name: Automation

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps here to build your project and generate artifacts
      - name: Build and create artifact
        run: |
          # Replace this with your build command
          echo "Building the project"
          mkdir -p output
          echo '{"version":"3.12.2","seed":13115,"examples":[{"id":"./spec/lib/sanction_scanner/v1/client_spec.rb[1:1:1:1]","description":"is expected to eq {\"errorCode\"=>nil, \"errorMessage\"=>nil, \"extraInfo\"=>nil, \"httpStatusCode\"=>200, \"isSuccess\"=>true, \"...>\"High\", \"triggeredRulesList\"=>[{\"ruleKey\"=>\"64b6b92f-4145-465b-8677-331a5f40d5d3\", \"score\"=>200}]}}","full_description":"SanctionScanner::V1::Client#execute_transaction when 200 sanction scanner response is expected to eq {\"errorCode\"=>nil, \"errorMessage\"=>nil, \"extraInfo\"=>nil, \"httpStatusCode\"=>200, \"isSuccess\"=>true, \"...>\"High\", \"triggeredRulesList\"=>[{\"ruleKey\"=>\"64b6b92f-4145-465b-8677-331a5f40d5d3\", \"score\"=>200}]}}","status":"passed","file_path":"./spec/lib/sanction_scanner/v1/client_spec.rb","line_number":58,"run_time":0.150965761,"pending_message":null}]}' > output/artifact1.json
          echo '{"version":"3.12.2","seed":36689,"examples":[{"id":"./spec/serializers/sms_log_serializer_spec.rb[1:1]","description":"is expected to eql {:created_at=>2024-07-02 12:57:57.319434000 +0000, :external_id=>nil, :id=>1, :log_type=>\"phone_otp\",...456789\", :resource_id=>1, :resource_type=>\"Order\", :updated_at=>2024-07-02 12:57:57.319434000 +0000}","full_description":"SmsLogSerializer is expected to eql {:created_at=>2024-07-02 12:57:57.319434000 +0000, :external_id=>nil, :id=>1, :log_type=>\"phone_otp\",...456789\", :resource_id=>1, :resource_type=>\"Order\", :updated_at=>2024-07-02 12:57:57.319434000 +0000}","status":"passed","file_path":"./spec/serializers/sms_log_serializer_spec.rb","line_number":23,"run_time":0.514871951,"pending_message":null}]}' > output/artifact2.json

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output/
