name: Upload license

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      project_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  upload-license:
    name: Upload license csv
    runs-on: [self-hosted, shared-gcp]
    container:
      image: python:3.10
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
    env:
      ARTIFACT_NAME: ${{inputs.artifact_name}}
      BRANCH_NAME: ${{inputs.branch_name}}
      GITHUB_COMMIT_ID: ${{inputs.commit_id}}
      PROJECT_NAME: ${{inputs.project_name}}
      REPOSITORY_NAME: ${{inputs.repository_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip pandas
      - uses: actions/download-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .
      - name: Set commit ID
        run: |
          # Set the commit timestamp
          echo "COMMIT_TIMESTAMP=$(date +'%Y/%m/%d')" >> "$GITHUB_ENV"

          # Timestamp s3 path
          echo "S3_DATE=$(date +'%d')" >> $GITHUB_ENV
          echo "S3_MONTH=$(date +'%m')" >> $GITHUB_ENV
          echo "S3_YEAR=$(date +'%Y')" >> $GITHUB_ENV
      - name: Update license csv
        run: |

          python3 <<HEREDOC
          import os
          import pandas as pd

          # Get the GitHub commit ID  & branch from environment variable
          github_commit_id = os.environ.get("GITHUB_COMMIT_ID")
          github_branch = os.environ.get("BRANCH_NAME")
          github_repo = os.environ.get("REPOSITORY_NAME")
          project_name = os.environ.get("PROJECT_NAME")
          commit_timestamp = os.environ.get("COMMIT_TIMESTAMP")

          licenses = {
              'Apache 2.0': ['Apache 2.0', 'Apache License (2.0)'],
              'BSD-2-Clause': ['BSD-2-Clause'],
              'Simplified BSD': ['Simplified BSD','Simplified BSD,ruby'],
              'New BSD': ['New BSD'],
              'LGPL': ['LGPL'],
              'GPL-3': ['GPL-3.0', 'GPL-3'],
              'GPL-2': ['GPL-2.0', 'GPL-2','GPL-2.0-or-later','GPL-2.0,GPL-3.0,PRAWN','GPL-2,GPL-3,ruby']
          }

          inverted_licenses = {syn: key for key, syns in licenses.items() for syn in syns}


          # Read the CSV file into a DataFrame
          df = pd.read_csv("license_report.csv", header=None, names=["package_name", "version", "license", "commit_id", "branch", "timestamp", "repository", "project"])

          # Cleanup license column
          df["license"] = df["license"].replace(inverted_licenses)

          # Add a new column with the current GitHub commit
          df["commit_id"] = github_commit_id

          df["branch"] = github_branch

          df["timestamp"] = commit_timestamp

          df["repository"] = github_repo

          df["project"] = project_name

          df.to_csv("license_report.csv", index=False)
          HEREDOC

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: upload the license report
        with:
          command: cp
          source: license_report.csv
          destination: "s3://licenses-prod/${{inputs.project_name}}/year=${{env.S3_YEAR}}/month=${{env.S3_MONTH}}/day=${{env.S3_DATE}}/${{env.GITHUB_COMMIT_ID}}.csv"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
