name: Upload Tests
on:
  workflow_run:
    workflows: ["Automation"]
    types:
      - completed
jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: downloaded-artifacts

      # Add steps here to use the downloaded artifact
      - name: List files in downloaded-artifacts
        run: ls -l downloaded-artifacts
