name: Upload Tests
on:
  workflow_run:
    workflows: ["Automation"]
    types:
      - completed

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the latest workflow run ID
        id: get_run_id
        run: |
          run_id=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=main&status=success" | \
                    jq -r '.workflow_runs[0].id')
          
          artifact_id=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                       "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/artifacts" | \
                       jq -r '.artifacts[] | select(.name=="my-artifact") | .id')

          curl -L -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -o artifact.zip \
               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip"
          unzip artifact.zip -d downloaded-artifacts

      - name: List files in downloaded-artifacts
        run: ls -l downloaded-artifacts
