name: Download Artifacts on PR Merge

on:
  push:
    branches:
      - master

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Get PR details
        id: get_pr
        uses: octokit/request-action@v2
        with:
          route: GET /repos/:repository/pulls?state=closed&sort=updated&direction=desc
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Parse PR details
        id: parse_pr
        run: |
          import json
          pr_data = json.loads('${{ steps.get_pr.outputs.data }}')
          for pr in pr_data:
            if pr['merged_at'] and pr['merge_commit_sha'] == '${{ github.sha }}':
              print(f"::set-output name=pr_number::{pr['number']}")
              print(f"::set-output name=head_sha::{pr['head']['sha']}")
              break
        shell: python

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./artifact
