name: Upload Tests
on:
  workflow_run:
    workflows: ["Automation"]
    types:
      - completed

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get the latest workflow run ID
        id: get_run_id
        run: |
          run_id=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=main&status=success" | \
                    jq -r '.workflow_runs[0].id')
          echo $run_id
          echo "run_id=$run_id" >> $GITHUB_ENV
          ecno $GITHUB_ENV

      - name: Get the artifact ID
        id: get_artifact_id
        run: |
          artifact_id=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                       "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ env.run_id }}/artifacts" | \
                       jq -r '.artifacts[] | select(.name=="my-artifact") | .id')
          echo "artifact_id=$artifact_id" >> $GITHUB_ENV

      - name: Download the artifact
        run: |
          curl -L -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -o artifact.zip \
               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.artifact_id }}/zip"
          unzip artifact.zip -d downloaded-artifacts

      - name: List files in downloaded-artifacts
        run: ls -l downloaded-artifacts
