name: Download Artifacts on PR Merge

on:
  push:
    branches:
      - master

jobs:
  download-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: get_branch_to_run
        run: |
           BRANCH=$(git branch -r --sort=-committerdate --format='%(HEAD)%(refname:short)' | head -2 | tail -1)
           echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Get the list of artifacts
        id: get_artifacts
        uses: octokit/request-action@v2.3.1
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts?branch=${{ env.BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: list artifacts
        run: |
           ls -l
