name: Download Artifacts on PR Merge

on:
  push:
    branches:
      - master

jobs:
  download-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: get_branch_to_run
        run: |
           BRANCH=$(git branch -r --sort=-committerdate --format='%(HEAD)%(refname:short)' |  head -2 | tail -1)
           echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Get the list of artifacts
        id: get_artifacts
        uses: octokit/request-action@v2.3.1
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts?branch=${{env.BRANCH}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Download artifact
        run: |
          # Extract the URL of the first artifact from the response
          ARTIFACT_URL=$(echo "${{ steps.get_artifacts.outputs.data }}" | jq -r '.artifacts[0].archive_download_url')
          echo "Downloading artifact from $ARTIFACT_URL"
          
          # Download the artifact using wget
          wget -q --show-progress --progress=bar:force:noscroll -O artifact.zip "$ARTIFACT_URL"

          # Unzip the artifact
          unzip -q artifact.zip -d artifact_folder  # Adjust the destination folder as per your need

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
