name: Download Artifacts on PR Merge

on:
  push:
    branches:
      - master

jobs:
  download-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: get_branch_to_run
        run: |
           BRANCH=$(git branch -r --sort=-committerdate --format='%(HEAD)%(refname:short)' | sed 's/origin\///' |  head -2 | tail -1)
           echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Get the list of artifacts
        id: get_artifacts
        uses: octokit/request-action@v2.3.1
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts?branch=${{env.BRANCH}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Download artifact
        run: |
          # Extract the URL of the first artifact from the response
          ARTIFACT_ID=$(echo '${{ steps.get_artifacts.outputs.data }}' | jq -r '.artifacts[]| select(.workflow_run.head_branch=="${{env.BRANCH}}")|.id')
          RUN_ID=$(echo '${{ steps.get_artifacts.outputs.data }}' | jq -r '.artifacts[]| select(.workflow_run.head_branch=="${{env.BRANCH}}")|.workflow_run.id')
          echo "Downloading artifact with ID $ARTIFACT_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          
          curl -L -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -o artifact.zip \
               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip"
          ls -l

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Download artifact GH
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          run-id: ${{env.RUN_ID}}
